# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170501_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('things', models.CharField(max_length=256, verbose_name='标题')),
                ('raw_url', models.CharField(max_length=256, verbose_name='引用地址')),
            ],
            options={
                'verbose_name_plural': '历史记录',
                'ordering': ['-date_time'],
                'verbose_name': '历史记录',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_title', models.CharField(max_length=128, verbose_name='标题')),
                ('src_marks', models.CharField(max_length=128, verbose_name='标记')),
                ('src_url', models.CharField(max_length=256, verbose_name='引用地址')),
                ('src_hint', models.CharField(max_length=256, verbose_name='显示地址')),
            ],
            options={
                'verbose_name_plural': '资源',
                'ordering': ['-src_title'],
                'verbose_name': '资源',
            },
        ),
        migrations.CreateModel(
            name='SourceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_class', models.CharField(max_length=128, verbose_name='类别')),
                ('intro', models.CharField(max_length=128, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '资源种类',
                'verbose_name': '资源种类',
            },
        ),
        migrations.AddField(
            model_name='source',
            name='src_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.SourceClass', verbose_name='归属类别'),
        ),
    ]
