# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170506_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-src_class'], 'verbose_name': '资源', 'verbose_name_plural': '资源'},
        ),
    ]
