# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170506_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-src_class', '-src_marks'], 'verbose_name': '\u8d44\u6e90', 'verbose_name_plural': '\u8d44\u6e90'},
        ),
    ]
